name: Deploys the application to dev

on:
  push:
    branches:
      - 'master'

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEV }}

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./.github/test
      - name: Deploy
        uses: ./.github/deploy
