name: Deploys the application to dev

on:
  push:
    branches:
      - 'master'

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./.github/test
